### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gauravirajput** [yoonwaiyan/java-bingo#1]
I have an error in BingoView at line no.87 and 152and BingoController program at line [no.11,12,14. @yoonwaiyan

**Comment by yoonwaiyan** [comment]
Sorry I'm not maintaining the codebase anymore, are you using Java SE 8 or different OS?

**Comment by Gauravirajput** [comment]
Linux6 redhat i solve the problem bt how to run this code on different lapy?

**Comment by yoonwaiyan** [comment]
@Gauravirajput You can run the same codebase from another computer using the same command with the same port number within LAN. I'm closing this issue for now, feel free to re-open if there's any further issue.

**Comment by Gauravirajput** [comment]
I try same cammond with same port number but its not working.

**Comment by yoonwaiyan** [comment]
Can you be more specific on "it's not working"?

**Comment by Gauravirajput** [comment]
Its not connenting to server n client and only show waiting for server n
client

**Comment by yoonwaiyan** [comment]
Couldn't help much though as I'm not sure how your screen looks like, how you run the command and I don't have an accessible Linux system here. Few months ago I've tried running this on Mac OS with Java SE 8 installed it runs good though. One of the possible cause is that the port is blocked by a firewall or other possible internet issue.

**Comment by Gauravirajput** [comment]
Ok no problem i will send u screeanshot tomorrow.
